# Generated by Django 3.1 on 2021-04-23 04:06

from django.db import migrations, models
import rock_paper_scissors.game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='score',
            name='computer_choice',
            field=models.CharField(choices=[(rock_paper_scissors.game.models.PlayerAction['Rock'], 0), (rock_paper_scissors.game.models.PlayerAction['Paper'], 1), (rock_paper_scissors.game.models.PlayerAction['Scissors'], 2)], max_length=3),
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='user_choice',
            field=models.CharField(choices=[(rock_paper_scissors.game.models.PlayerAction['Rock'], 0), (rock_paper_scissors.game.models.PlayerAction['Paper'], 1), (rock_paper_scissors.game.models.PlayerAction['Scissors'], 2)], max_length=3),
        ),
    ]
