# Generated by Django 3.1 on 2021-04-23 16:47

from django.db import migrations

def forwards_func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'initial.json')

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func,),
    ]
