# Generated by Django 3.1 on 2021-04-23 04:35

from django.db import migrations, models
import rock_paper_scissors.game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210423_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(choices=[(rock_paper_scissors.game.models.PlayerAction['Rock'], 0), (rock_paper_scissors.game.models.PlayerAction['Paper'], 1), (rock_paper_scissors.game.models.PlayerAction['Scissors'], 2)], max_length=3)),
            ],
        ),
    ]
