# Generated by Django 3.1 on 2021-04-23 05:00

from django.db import migrations, models
import rock_paper_scissors.game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playerchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchoice',
            name='user_choice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='computer_choice',
            field=models.CharField(choices=[(rock_paper_scissors.game.models.PlayerAction['Rock'], 2), (rock_paper_scissors.game.models.PlayerAction['Paper'], 3), (rock_paper_scissors.game.models.PlayerAction['Scissors'], 4)], max_length=3),
        ),
        migrations.AlterField(
            model_name='score',
            name='user_choice',
            field=models.CharField(choices=[(rock_paper_scissors.game.models.PlayerAction['Rock'], 2), (rock_paper_scissors.game.models.PlayerAction['Paper'], 3), (rock_paper_scissors.game.models.PlayerAction['Scissors'], 4)], max_length=3),
        ),
    ]
